export const USER_MANAGEMENT = {
  TITLE: 'Benutzerverwaltung',
  USER_ROLES_TITLE: 'Benutzerrollen',
  TABS: {
    OVERVIEW: 'Übersicht',
    ORDERS: 'Bestellungen',
    USERS: 'Benutzer',
    PRODUCTS: 'Produkte',
    LOCATIONS: 'Standorte',
    LOGISTICS: 'Logistik',
  },
  USERS_TABLE: {
    TITLE: 'Benutzerverwaltung',
    ADD_USER: 'Benutzer hinzufügen',
    COLUMNS: {
      USER_ID: 'Benutzer-ID',
      PROFILE_NAME: 'Profilname',
      TYPE: 'Typ',
      ACTIVE_LOCATIONS: 'Aktive Standorte',
      ORDERS: 'Bestellungen',
      TOTAL_PURCHASE_AMOUNT: 'Gesamtkaufsumme',
      LISTED_ARTICLES: 'Gelistete Artikel',
      SALES: 'Verkäufe',
      TOTAL_SALES_AMOUNT: 'Gesamtverkaufssumme',
      ACTIONS: 'Aktionen',
      STATUS: 'Status',
      JOIN_DATE: 'Beitrittsdatum',
    },
    FILTERS: {
      BUYER: 'Käufer',
      SELLER: 'Verkäufer',
      LOGISTIC_CARRIER: 'Logistik (Spediteur)',
    },
    TOOLTIPS: {
      VIEW_USER_DETAILS: 'Benutzerdetails anzeigen',
      WAREHOUSES: 'Lager: {warehouses}',
      NO_ACTIVE_WAREHOUSES: 'Keine aktiven Lager',
      COMPLETED_PURCHASES: '{count} abgeschlossene Käufe',
      TOTAL_SPENT: 'Gesamtausgaben seit Kontoerstellung: {amount} €',
      LISTED_ARTICLES_COUNT: '{count} verschiedene Artikel derzeit zum Verkauf gelistet',
      SALES_COMPLETED: '{count} Verkäufe abgeschlossen seit Kontoerstellung',
      TOTAL_REVENUE: 'Gesamtumsatz aus Verkäufen seit Kontoerstellung: {amount} €',
    },
    ACTIONS: {
      ADD_USER: 'Benutzer hinzufügen',
      VIEW_DETAILS: 'Benutzerdetails anzeigen',
    },
    PAGINATION: {
      TOTAL_TEXT: '{start}-{end} von {total} Benutzern',
      USERS: 'Benutzer',
    },
    EMPTY_STATE: {
      NO_USERS_FOUND: 'Keine Benutzer gefunden',
    },
    CONSOLE_MESSAGES: {
      ADD_NEW_USER: 'Neuen Benutzer hinzufügen',
    },
    CREATE_USER: 'Benutzer erstellen',
    MESSAGES: {
      CREATE_SUCCESS: 'Benutzer erfolgreich erstellt',
      CREATE_ERROR: 'Benutzer konnte nicht erstellt werden',
    },
  },
  PRODUCTS_TABLE: {
    TITLE: 'Produktverwaltung',
    COLUMNS: {
      ART_NR: 'Art-Nr',
      PICTURES: 'Bilder',
      TITLE: 'Titel',
      LOCATION: 'Standort',
      CROWD: 'Menge',
      SALES_VOLUME: 'Verkaufsvolumen',
      STATUS: 'Status',
      ACTIONS: 'Aktionen',
    },
    SEARCH: {
      PLACEHOLDER: 'Produkte suchen...',
      QUICK_SORT: 'Schnellsortierung',
    },
    SORT_OPTIONS: {
      SALES_HIGH_TO_LOW: 'Verkaufsvolumen (Hoch zu Niedrig)',
      SALES_LOW_TO_HIGH: 'Verkaufsvolumen (Niedrig zu Hoch)',
      LOCATIONS_HIGH_TO_LOW: 'Standorte (Hoch zu Niedrig)',
      LOCATIONS_LOW_TO_HIGH: 'Standorte (Niedrig zu Hoch)',
      QUANTITY_HIGH_TO_LOW: 'Menge (Hoch zu Niedrig)',
      QUANTITY_LOW_TO_HIGH: 'Menge (Niedrig zu Hoch)',
      PICTURES_HIGH_TO_LOW: 'Bilder (Hoch zu Niedrig)',
      PICTURES_LOW_TO_HIGH: 'Bilder (Niedrig zu Hoch)',
      TITLE_A_TO_Z: 'Titel (A-Z)',
      TITLE_Z_TO_A: 'Titel (Z-A)',
      ART_NR_A_TO_Z: 'Art-Nr (A-Z)',
      ART_NR_Z_TO_A: 'Art-Nr (Z-A)',
    },
    TOOLTIPS: {
      SORT_BY_ART_NR: 'Nach Artikelnummer sortieren',
      SORT_BY_PICTURES: 'Nach Bildanzahl sortieren',
      SORT_BY_TITLE: 'Nach Produkttitel sortieren',
      SORT_BY_LOCATIONS: 'Nach Standortanzahl sortieren',
      SORT_BY_QUANTITY: 'Nach verfügbarer Menge sortieren',
      SORT_BY_SALES_VOLUME: 'Nach Verkaufsvolumen sortieren',
      SORT_BY_STATUS: 'Nach Status sortieren',
      VIEW_PRODUCT_DETAILS: 'Produktdetails anzeigen',
      PICTURES_COUNT: '{count} Bild(er) verfügbar',
      AVAILABLE_IN_LOCATIONS: 'Verfügbar in {count} Standort(en)',
      QUANTITY_AVAILABLE: '{count} Einheiten derzeit verfügbar',
      TOTAL_REVENUE: 'Gesamtumsatz seit Produktstart: {amount} €',
      STATUS_ACTIVE: 'Produkt ist aktiv und für Benutzer sichtbar',
      STATUS_INACTIVE: 'Produkt ist inaktiv und für Benutzer verborgen',
    },
    FILTERS: {
      STATUS_ACTIVE: 'Aktiv',
      STATUS_INACTIVE: 'Inaktiv',
    },
    STATUS: {
      PRODUCTS_COUNT: '{count} Produkt(e) gefunden',
      SORTED: '(sortiert)',
    },
    PAGINATION: {
      SHOWING_TEXT: 'Zeige {start}-{end} von {total} Produkt(en)',
      PRODUCT_SINGULAR: 'Produkt',
      PRODUCT_PLURAL: 'Produkte',
    },
    EMPTY_STATE: {
      NO_PRODUCTS_FOUND: 'Keine Produkte gefunden',
      NO_PRODUCTS_MATCHING: 'Keine Produkte gefunden, die "{search}" entsprechen',
    },
    CONSOLE_MESSAGES: {
      VIEW_PRODUCT_DETAILS: 'Produktdetails anzeigen:',
      STATUS_CHANGED: 'Produktstatus geändert:',
    },
    MODAL: {
      TITLE: 'Produktdetails',
      FIELDS: {
        ART_NR: 'Artikelnummer',
        TITLE: 'Produkttitel',
        STATUS: 'Status',
        PICTURES: 'Bilder',
        LOCATIONS: 'Verfügbare Standorte',
        QUANTITY: 'Verfügbare Menge',
        SALES_VOLUME: 'Gesamtverkaufsvolumen',
        DESCRIPTION: 'Beschreibung',
        CATEGORY: 'Kategorie',
        MANUFACTURER: 'Hersteller',
        PRICE: 'Stückpreis',
        CREATED_DATE: 'Erstellungsdatum',
        LAST_UPDATED: 'Zuletzt aktualisiert',
      },
    },
  },
  LOCATIONS_TABLE: {
    TITLE: 'Standortverwaltung',
    PLACEHOLDERS: {
      SEARCH: 'Standorte suchen...',
      NAME: 'Standortnamen eingeben',
      ADDRESS: 'Standortadresse eingeben',
      TYPE: 'Standorttyp auswählen',
    },
    ACTIONS: {
      ADD: 'Standort hinzufügen',
      ASSIGN: 'Standort zuweisen',
      EDIT: 'Bearbeiten',
    },
    ERRORS: {
      NAME: 'Bitte geben Sie einen Standortnamen ein',
      ADDRESS: 'Bitte geben Sie eine Standortadresse ein',
      TYPE: 'Bitte wählen Sie einen Standorttyp',
    },
    COLUMNS: {
      NAME: 'Name',
      ADDRESS: 'Adresse',
      TYPE: 'Typ',
      STATUS: 'Status',
      LOCATION_ID: 'Standort-ID',
      USER: 'Benutzer',
      AREA: 'Bereich',
      COVER: 'Abdeckung',
      ARTICLES: 'Artikel',
      LOGISTIC: 'Logistik',
      SALES_VOLUME: 'Verkaufsvolumen',
      DATE_CREATED: 'Erstellungsdatum',
      ACTIONS: 'Aktionen',
    },
    SEARCH: {
      PLACEHOLDER: 'Standorte suchen...',
      QUICK_SORT: 'Schnellsortierung',
    },
    SORT_OPTIONS: {
      NEWEST_FIRST: 'Neueste zuerst',
      OLDEST_FIRST: 'Älteste zuerst',
      SALES_HIGH_TO_LOW: 'Verkaufsvolumen (Hoch zu Niedrig)',
      SALES_LOW_TO_HIGH: 'Verkaufsvolumen (Niedrig zu Hoch)',
      MOST_ARTICLES: 'Meiste Artikel',
      FEWEST_ARTICLES: 'Wenigste Artikel',
      USER_NAME_A_TO_Z: 'Benutzername (A-Z)',
      USER_NAME_Z_TO_A: 'Benutzername (Z-A)',
    },
    TOOLTIPS: {
      SORT_BY_LOCATION_ID: 'Nach Standort-ID sortieren',
      SORT_BY_USER_NAME: 'Nach Benutzername sortieren',
      SORT_BY_AREA: 'Nach Bereich sortieren',
      SORT_BY_COVERAGE: 'Nach Abdeckung sortieren',
      SORT_BY_ARTICLE_COUNT: 'Nach Artikelanzahl sortieren',
      SORT_BY_LOGISTIC_TYPE: 'Nach Logistiktyp sortieren',
      SORT_BY_SALES_VOLUME: 'Nach Verkaufsvolumen sortieren',
      SORT_BY_CREATION_DATE: 'Nach Erstellungsdatum sortieren (Älteste/Neueste)',
      VIEW_LOCATION_DETAILS: 'Standortdetails anzeigen',
      TOTAL_REVENUE: 'Gesamtumsatz: {amount} €',
      ESTABLISHED: 'Erstellt am: {date}',
    },
    FILTERS: {
      COVER_YES: 'Ja',
      COVER_NO: 'Nein',
    },
    STATUS: {
      LOCATION_COUNT: '{count} Standort{e} gefunden',
      SORTED: '(sortiert)',
      ACTIVE: 'Aktiv',
      INACTIVE: 'Inaktiv',
      MAINTENANCE: 'Wartung',
    },
    PAGINATION: {
      SHOWING_TEXT: 'Zeige {start}-{end} von {total} Standort{e}',
      LOCATION_SINGULAR: 'Standort',
      LOCATION_PLURAL: 'Standorte',
    },
    EMPTY_STATE: {
      NO_LOCATIONS_FOUND: 'Keine Standorte gefunden',
      NO_LOCATIONS_MATCHING: 'Keine Standorte gefunden, die "{search}" entsprechen',
    },
    CONSOLE_MESSAGES: {
      VIEW_LOCATION_DETAILS: 'Standortdetails anzeigen:',
      LOCATION_ID_CLICKED: 'Standort-ID geklickt:',
    },
    MODAL: {
      TITLE: {
        ADD: 'Neuen Standort hinzufügen',
        ASSIGN: 'Bestehenden Standort zuweisen',
        EDIT: 'Standort bearbeiten',
        DEFAULT: 'Standort',
      },
      FIELDS: {
        SELECT_LOCATION: 'Standort auswählen',
        ASSIGNMENT_TYPE: 'Zuweisungstyp',
        LOCATION_ID: 'Standort-ID',
        NAME: 'Standortname',
        ADDRESS: 'Adresse',
        TYPE: 'Standorttyp',
        STATUS: 'Status',
      },
      PLACEHOLDERS: {
        SELECT_LOCATION: 'Aus bestehenden Standorten wählen',
        ASSIGNMENT_TYPE: 'Zuweisungstyp auswählen',
        LOCATION_ID: 'z.B. LOC001',
        NAME: 'z.B. Hauptsitz, Lager A',
        ADDRESS: 'Vollständige Adresse inkl. Straße, Stadt, Bundesland, PLZ',
        TYPE: 'Typ auswählen',
      },
      ERRORS: {
        SELECT_LOCATION: 'Bitte wählen Sie einen Standort',
        ASSIGNMENT_TYPE: 'Bitte wählen Sie einen Zuweisungstyp',
        LOCATION_ID: 'Bitte geben Sie eine Standort-ID ein',
        NAME: 'Bitte geben Sie einen Standortnamen ein',
        ADDRESS: 'Bitte geben Sie eine Adresse ein',
        TYPE: 'Bitte wählen Sie einen Standorttyp',
        STATUS: 'Bitte wählen Sie einen Status',
      },
    },
    ASSIGNMENT_TYPES: {
      PRIMARY: 'Primärer Standort',
      SECONDARY: 'Sekundärer Standort',
      TEMPORARY: 'Temporärer Zugang',
    },
    TYPES: {
      OFFICE: 'Büro',
      WAREHOUSE: 'Lager',
      DISTRIBUTION_CENTER: 'Verteilzentrum',
      RETAIL_STORE: 'Einzelhandelsgeschäft',
      MANUFACTURING: 'Produktionsstätte',
    },
    MESSAGES: {
      ADD_SUCCESS: 'Standort erfolgreich hinzugefügt!',
      ASSIGN_SUCCESS: 'Standort erfolgreich zugewiesen!',
      UPDATE_SUCCESS: 'Standort erfolgreich aktualisiert!',
    },
  },
  LOGISTICS_TABLE: {
    TITLE: 'Logistikverwaltung',
    COLUMNS: {
      LOGISTIC_NR: 'Logistik-Nr',
      NAME: 'Name',
      TYPE: 'Typ',
      REGION: 'Region',
      LOCATION: 'Standort',
      TOURS: 'Touren',
      SALES_VOLUME: 'Verkaufsvolumen',
      ACTIONS: 'Aktionen',
    },
    SEARCH: {
      PLACEHOLDER: 'Logistikunternehmen suchen...',
      QUICK_SORT: 'Schnellsortierung',
    },
    SORT_OPTIONS: {
      NEWEST_FIRST: 'Neueste zuerst',
      OLDEST_FIRST: 'Älteste zuerst',
      SALES_HIGH_TO_LOW: 'Verkaufsvolumen (Hoch zu Niedrig)',
      SALES_LOW_TO_HIGH: 'Verkaufsvolumen (Niedrig zu Hoch)',
      MOST_TOURS: 'Meiste Touren',
      FEWEST_TOURS: 'Wenigste Touren',
      MOST_REGIONS: 'Meiste Regionen',
      FEWEST_REGIONS: 'Wenigste Regionen',
      NAME_A_TO_Z: 'Name (A-Z)',
      NAME_Z_TO_A: 'Name (Z-A)',
    },
    TOOLTIPS: {
      SORT_BY_LOGISTIC_NR: 'Nach Logistiknummer sortieren',
      SORT_BY_NAME: 'Nach Name sortieren',
      SORT_BY_TYPE: 'Nach Typ sortieren',
      SORT_BY_REGIONS: 'Nach Regionenanzahl sortieren',
      SORT_BY_LOCATIONS: 'Nach Standortanzahl sortieren',
      SORT_BY_TOURS: 'Nach Tourenanzahl sortieren',
      SORT_BY_SALES_VOLUME: 'Nach Verkaufsvolumen sortieren',
      VIEW_LOGISTICS_DETAILS: 'Logistikdetails anzeigen',
      TOTAL_REVENUE: 'Gesamtumsatz: {amount} €',
      COVERS_REGIONS: 'Deckt {count} Regionen ab',
      COVERS_LOCATIONS: 'Deckt {count} Standorte ab',
      TOURS_COMPLETED: '{count} Touren abgeschlossen',
    },
    STATUS: {
      LOGISTICS_COUNT: '{count} Logistikunternehmen gefunden',
      SORTED: '(sortiert)',
    },
    PAGINATION: {
      SHOWING_TEXT: 'Zeige {start}-{end} von {total} Logistikunternehmen',
      LOGISTICS_SINGULAR: 'Logistikunternehmen',
      LOGISTICS_PLURAL: 'Logistikunternehmen',
    },
    EMPTY_STATE: {
      NO_LOGISTICS_FOUND: 'Keine Logistikunternehmen gefunden',
      NO_LOGISTICS_MATCHING: 'Keine Logistikunternehmen gefunden, die "{search}" entsprechen',
    },
    CONSOLE_MESSAGES: {
      VIEW_LOGISTICS_DETAILS: 'Logistikdetails anzeigen:',
      LOGISTICS_ID_CLICKED: 'Logistik-ID angeklickt:',
    },
    MODAL: {
      TITLE: 'Logistikdetails',
      FIELDS: {
        LOGISTIC_NR: 'Logistiknummer',
        NAME: 'Firmenname',
        TYPE: 'Servicetyp',
        STATUS: 'Status',
        ADDRESS: 'Adresse',
        PHONE: 'Telefon',
        EMAIL: 'E-Mail',
        REGIONS: 'Regionenabdeckung',
        LOCATIONS: 'Standortabdeckung',
        TOURS: 'Gesamttouren',
        SALES_VOLUME: 'Verkaufsvolumen',
        ESTABLISHED_DATE: 'Gründungsdatum',
        LAST_ACTIVITY: 'Letzte Aktivität',
      },
    },
  },
  USER_DETAILS_MODAL: {
    TITLE: 'Benutzerdetails',
    COMPANY_DATA: 'Firmendaten',
    ERRORS: {
      COMPANY_NAME: 'Bitte geben Sie einen Firmennamen ein',
      COMPANY_ID: 'Bitte geben Sie eine Firmen-ID ein',
      COMPANY_PHONE: 'Bitte geben Sie eine Telefonnummer ein',
      COMPANY_FAX: 'Bitte geben Sie eine Faxnummer ein',
      COMPANY_EMAIL: 'Bitte geben Sie eine E-Mail-Adresse ein',
    },
    PLACEHOLDERS: {
      COMPANY_NAME: 'Firmennamen eingeben',
      COMPANY_ID: 'Firmen-ID eingeben',
      COMPANY_PHONE: 'Telefonnummer eingeben',
      COMPANY_FAX: 'Faxnummer eingeben',
      COMPANY_EMAIL: 'E-Mail-Adresse eingeben',
      ADDRESS: 'Adresse eingeben',
    },
    LABELS: {
      COMPANY_NAME: 'Firmennamen',
      COMPANY_ID: 'Firmen-ID',
      COMPANY_PHONE: 'Telefonnummer',
      COMPANY_FAX: 'Faxnummer',
      COMPANY_EMAIL: 'E-Mail-Adresse',
      ADDRESS: 'Adresse',
      USER_ID: 'Benutzer-ID',
      FIRST_NAME: 'Vorname',
      LAST_NAME: 'Nachname',
      PROFILE_NAME: 'Profilname',
      EMAIL: 'E-Mail',
      PHONE: 'Telefon',
      MOBILE: 'Mobiltelefon',
      FAX: 'Fax',
      USER_TYPES: 'Benutzertypen',
      ROLE: 'Rolle',
      STATUS: 'Status',
      DEPARTMENT: 'Abteilung',
      LOCATION: 'Standort',
      JOIN_DATE: 'Beitrittsdatum',
      LAST_LOGIN: 'Letzte Anmeldung',
      ACTIVE_WAREHOUSES: 'Aktive Lager',
      TOTAL_ORDERS: 'Gesamtbestellungen',
      TOTAL_PURCHASE_AMOUNT: 'Gesamtkaufsumme',
      LISTED_ARTICLES: 'Gelistete Artikel',
      TOTAL_SALES: 'Gesamtverkäufe',
      TOTAL_SALES_AMOUNT: 'Gesamtverkaufssumme',
      ROLE_ADMINISTRATION_IT: 'Administration IT ',
      ROLE_AREA_MANAGEMENT: 'Bereichsleitung',
      ROLE_OPERATIONS_MANAGEMENT: 'Betriebsleitung',
      ROLE_ACCOUNTING: 'Buchhaltung',
      ROLE_CONTROLLING: 'Controlling',
      ROLE_LOGISTICS_COORDINATOR: 'Disposition',
      ROLE_PURCHASING: 'Einkauf',
      ROLE_MANAGEMENT: 'Geschäftsführung',
      ROLE_CUSTOMER_SUPPORT: 'Kundenbetreuung',
      ROLE_WAREHOUSING: 'Lagerist',
      ROLE_WAREHOUSE_MANAGEMENT: 'Lagerleitung',
      ROLE_LOGISTICS: 'Logistik',
      ROLE_PROJECT_MANAGEMENT: 'Projektleitung',
      ROLE_ADMINISTRATIVE: 'Sachbearbeitung',
      ROLE_SECRETARY: 'Sekretariat',
      ROLE_SALES: 'Verkauf',
    },
    NO_ACTIVE_WAREHOUSES: 'Keine aktiven Lager',
  },
  CONTACT_PERSONS_TABLE: {
    TITLE: 'Kontaktpersonen',
    COLUMNS: {
      CONTACT_ID: 'Kontakt-ID',
      FIRST_NAME: 'Vorname',
      LAST_NAME: 'Nachname',
      EMAIL: 'E-Mail',
      PHONE: 'Telefon',
      POSITION: 'Position',
      DEPARTMENT: 'Abteilung',
      STATUS: 'Status',
      ACTIONS: 'Aktionen',
    },
    LABELS: {
      FIRST_NAME: 'Vorname',
      LAST_NAME: 'Nachname',
      EMAIL: 'E-Mail',
      PHONE: 'Telefon',
      POSITION: 'Position',
      DEPARTMENT: 'Abteilung',
      SEARCH: 'Kontakte suchen',
    },
    PLACEHOLDERS: {
      FIRST_NAME: 'Vorname eingeben',
      LAST_NAME: 'Nachname eingeben',
      EMAIL: 'E-Mail-Adresse eingeben',
      PHONE: 'Telefonnummer eingeben',
      POSITION: 'Position eingeben',
      DEPARTMENT: 'Abteilung eingeben',
      SEARCH: 'Kontakte suchen...',
    },
    ERRORS: {
      FIRST_NAME: 'Bitte geben Sie den Vornamen ein!',
      LAST_NAME: 'Bitte geben Sie den Nachnamen ein!',
      EMAIL: 'Bitte geben Sie eine E-Mail-Adresse ein!',
      EMAIL_INVALID: 'Bitte geben Sie eine gültige E-Mail-Adresse ein!',
      PHONE: 'Bitte geben Sie eine Telefonnummer ein!',
      POSITION: 'Bitte geben Sie die Position ein!',
      DEPARTMENT: 'Bitte geben Sie die Abteilung ein!',
    },
    ACTIONS: {
      ADD: 'Kontakt hinzufügen',
      ASSIGN: 'Kontakt zuweisen',
      EDIT: 'Bearbeiten',
    },
  },
  COMMON: {
    CANCEL: 'Abbrechen',
    RESET: 'Zurücksetzen',
    CONFIRM_DISCARD_TITLE: 'Änderungen verwerfen?',
    CONFIRM_DISCARD_MESSAGE: 'Sind Sie sicher, dass Sie Ihre Änderungen verwerfen möchten?',
    DISCARD: 'Verwerfen',
  },
  EMPLOYEES_TABLE: {
    TITLE: 'Mitarbeiter',
    COLUMNS: {
      NAME: 'Name',
      POSITION: 'Position',
      EMAIL: 'E-Mail',
      PHONE: 'Telefon',
      LOCATION: 'Standort',
      STATUS: 'Status',
      ACTIONS: 'Aktionen',
    },
    LABELS: {
      NAME: 'Name',
      POSITION: 'Position',
      EMAIL: 'E-Mail',
      PHONE: 'Telefon',
      LOCATION: 'Standort',
      STATUS: 'Status',
      SEARCH: 'Mitarbeiter suchen',
    },
    PLACEHOLDERS: {
      NAME: 'Namen eingeben',
      POSITION: 'Position eingeben',
      EMAIL: 'E-Mail-Adresse eingeben',
      PHONE: 'Telefonnummer eingeben',
      LOCATION: 'Standort auswählen',
      SEARCH: 'Mitarbeiter suchen...',
    },
    ERRORS: {
      NAME: 'Bitte geben Sie den Namen ein!',
      POSITION: 'Bitte geben Sie die Position ein!',
      EMAIL: 'Bitte geben Sie eine E-Mail-Adresse ein!',
      EMAIL_INVALID: 'Bitte geben Sie eine gültige E-Mail-Adresse ein!',
      PHONE: 'Bitte geben Sie eine Telefonnummer ein!',
      LOCATION: 'Bitte wählen Sie einen Standort aus!',
    },
    ACTIONS: {
      ADD: 'Mitarbeiter hinzufügen',
      EDIT: 'Bearbeiten',
      DELETE: 'Löschen',
    },
    STATUS: {
      ACTIVE: 'Aktiv',
      INACTIVE: 'Inaktiv',
    },
    EMPTY_STATE: {
      NO_EMPLOYEES: 'Keine Mitarbeiter gefunden',
      NO_LOCATIONS: 'Bitte fügen Sie zuerst Standorte hinzu, um Mitarbeiter zu verwalten',
    },
    MESSAGES: {
      ADD_SUCCESS: 'Mitarbeiter erfolgreich hinzugefügt',
      UPDATE_SUCCESS: 'Mitarbeiter erfolgreich aktualisiert',
      DELETE_SUCCESS: 'Mitarbeiter erfolgreich gelöscht',
      ADD_ERROR: 'Mitarbeiter konnte nicht hinzugefügt werden',
      UPDATE_ERROR: 'Mitarbeiter konnte nicht aktualisiert werden',
      DELETE_ERROR: 'Mitarbeiter konnte nicht gelöscht werden',
    },
    MODAL: {
      TITLE: {
        ADD: 'Neuen Mitarbeiter hinzufügen',
        EDIT: 'Mitarbeiter bearbeiten',
      },
      FIELDS: {
        NAME: 'Mitarbeitername',
        POSITION: 'Position',
        EMAIL: 'E-Mail-Adresse',
        PHONE: 'Telefonnummer',
        LOCATION: 'Standort',
        STATUS: 'Status',
      },
      ERRORS: {
        NAME: 'Bitte geben Sie den Mitarbeiternamen ein',
        POSITION: 'Bitte geben Sie die Position ein',
        EMAIL: 'Bitte geben Sie eine E-Mail-Adresse ein',
        EMAIL_INVALID: 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
        PHONE: 'Bitte geben Sie eine Telefonnummer ein',
        LOCATION: 'Bitte wählen Sie einen Standort aus',
        STATUS: 'Bitte wählen Sie einen Status aus',
      },
      PLACEHOLDERS: {
        NAME: 'Vollständiger Name',
        POSITION: 'Jobtitel',
        EMAIL: 'E-Mail-Adresse',
        PHONE: 'Telefonnummer',
        LOCATION: 'Standort auswählen',
      },
    },
  },
  EDIT_USER_FORM: {
    TITLE: 'Benutzer bearbeiten',
    TABS: {
      DETAILS: 'Details',
      LOCATION: 'Standort',
      EMPLOYEES: 'Mitarbeiter',
      ORDERS: 'Bestellhistorie',
      SALES: 'Verkaufshistorie',
      OFFERINGS: 'Angebote',
      ORG_CHART: 'Organigramm',
    },
    MESSAGES: {
      UPDATE_SUCCESS: 'Benutzer erfolgreich aktualisiert',
      UPDATE_ERROR: 'Benutzer konnte nicht aktualisiert werden',
      LOAD_ERROR: 'Benutzerdaten konnten nicht geladen werden',
      USER_NOT_FOUND: 'Benutzer nicht gefunden',
    },
    BUTTONS: {
      SAVE: 'Speichern',
      CANCEL: 'Abbrechen',
      BACK: 'Zurück zur Benutzerliste',
    },
    LOADING: {
      FETCHING: 'Benutzerdaten werden geladen...',
      SAVING: 'Änderungen werden gespeichert...',
    },
  },
  ORDER_HISTORY: {
    TITLE: 'Bestellhistorie',
    SUBTITLE: 'Alle vergangenen und aktuellen Bestellungen',
    NO_ORDERS: 'Keine Bestellungen gefunden',
    STATUS: {
      PENDING: 'Ausstehend',
      PROCESSING: 'In Bearbeitung',
      SHIPPED: 'Versendet',
      DELIVERED: 'Geliefert',
      CANCELLED: 'Storniert',
      REFUNDED: 'Rückerstattet',
    },
  },
  SALES_HISTORY: {
    TITLE: 'Verkaufshistorie',
    SUBTITLE: 'Alle vergangenen und aktuellen Verkäufe',
    NO_SALES: 'Keine Verkäufe gefunden',
    COMPLETED_SALES: 'Abgeschlossene Verkäufe',
    TOTAL_REVENUE: 'Gesamtumsatz',
    STATUS: {
      PENDING: 'Ausstehend',
      PROCESSING: 'In Bearbeitung',
      SHIPPED: 'Versendet',
      DELIVERED: 'Geliefert',
      CANCELLED: 'Storniert',
      REFUNDED: 'Rückerstattet',
    },
  },
  OFFERINGS: {
    TITLE: 'Aktuelle Angebote',
    SUBTITLE: 'Alle aktuellen Angebote mit ihren jeweiligen Mengen',
    NO_OFFERINGS: 'Keine Angebote gefunden',
    TOTAL_ITEMS: 'Gesamtartikel',
    TOTAL_QUANTITY: 'Gesamtmenge',
    COLUMNS: {
      ITEM_NAME: 'Artikelname',
      CATEGORY: 'Kategorie',
      QUANTITY: 'Menge',
      PRICE: 'Preis',
      LOCATION: 'Standort',
      STATUS: 'Status',
    },
    STATUS: {
      ACTIVE: 'Aktiv',
      INACTIVE: 'Inaktiv',
      OUT_OF_STOCK: 'Nicht verfügbar',
    },
  },
  ORGANIZATIONAL_CHART: {
    TITLE: 'Organigramm',
    SUBTITLE: 'Unternehmensstruktur mit Standorten und Mitarbeitern',
    NO_DATA: 'Keine Organisationsdaten verfügbar',
    LOCATION: {
      HEAD: 'Hauptstandort',
      BRANCH: 'Niederlassung',
    },
    EMPLOYEE: {
      POSITION: 'Position',
      DEPARTMENT: 'Abteilung',
    },
  },
};
