export const USER_MANAGEMENT = {
  TITLE: 'User Management',
  USER_ROLES_TITLE: 'User Roles',
  TABS: {
    OVERVIEW: 'Overview',
    ORDERS: 'Orders',
    USERS: 'Users',
    PRODUCTS: 'Products',
    LOCATIONS: 'Locations',
    LOGISTICS: 'Logistics',
  },
  USERS_TABLE: {
    TITLE: 'User Management',
    ADD_USER: 'Add User',
    CREATE_USER: 'Create User',
    COLUMNS: {
      USER_ID: 'User ID',
      PROFILE_NAME: 'Profile Name',
      TYPE: 'Type',
      ACTIVE_LOCATIONS: 'Active Locations',
      ORDERS: 'Orders',
      TOTAL_PURCHASE_AMOUNT: 'Total Purchase Amount',
      LISTED_ARTICLES: 'Listed Articles',
      SALES: 'Sales',
      TOTAL_SALES_AMOUNT: 'Total Sales Amount',
      ACTIONS: 'Actions',
      STATUS: 'Status',
      JOIN_DATE: 'Join Date',
    },
    FILTERS: {
      BUYER: 'Buyer',
      SELLER: 'Seller',
      LOGISTIC_CARRIER: 'Logistic (carrier)',
    },
    TOOLTIPS: {
      VIEW_USER_DETAILS: 'View user details',
      WAREHOUSES: 'Warehouses: {warehouses}',
      NO_ACTIVE_WAREHOUSES: 'No active warehouses',
      COMPLETED_PURCHASES: '{count} completed purchases',
      TOTAL_SPENT: 'Total spent since account creation: {amount} €',
      LISTED_ARTICLES_COUNT: '{count} different articles currently listed for sale',
      SALES_COMPLETED: '{count} sales completed since account creation',
      TOTAL_REVENUE: 'Total revenue from sales since account creation: {amount} €',
    },
    ACTIONS: {
      ADD_USER: 'Add User',
      VIEW_DETAILS: 'View user details',
    },
    PAGINATION: {
      TOTAL_TEXT: '{start}-{end} of {total} users',
      USERS: 'users',
    },
    EMPTY_STATE: {
      NO_USERS_FOUND: 'No users found',
    },
    CONSOLE_MESSAGES: {
      ADD_NEW_USER: 'Add new user',
    },
    MESSAGES: {
      CREATE_SUCCESS: 'User created successfully',
      CREATE_ERROR: 'Failed to create user',
    },
  },
  PRODUCTS_TABLE: {
    TITLE: 'Products Management',
    COLUMNS: {
      ART_NR: 'Art-Nr',
      PICTURES: 'Pictures',
      TITLE: 'Title',
      LOCATION: 'Location',
      CROWD: 'Crowd',
      SALES_VOLUME: 'Sales Volume',
      STATUS: 'Status',
      ACTIONS: 'Actions',
    },
    SEARCH: {
      PLACEHOLDER: 'Search products...',
      QUICK_SORT: 'Quick Sort',
    },
    SORT_OPTIONS: {
      SALES_HIGH_TO_LOW: 'Sales Volume (High to Low)',
      SALES_LOW_TO_HIGH: 'Sales Volume (Low to High)',
      LOCATIONS_HIGH_TO_LOW: 'Locations (High to Low)',
      LOCATIONS_LOW_TO_HIGH: 'Locations (Low to High)',
      QUANTITY_HIGH_TO_LOW: 'Quantity (High to Low)',
      QUANTITY_LOW_TO_HIGH: 'Quantity (Low to High)',
      PICTURES_HIGH_TO_LOW: 'Pictures (High to Low)',
      PICTURES_LOW_TO_HIGH: 'Pictures (Low to High)',
      TITLE_A_TO_Z: 'Title (A-Z)',
      TITLE_Z_TO_A: 'Title (Z-A)',
      ART_NR_A_TO_Z: 'Art-Nr (A-Z)',
      ART_NR_Z_TO_A: 'Art-Nr (Z-A)',
    },
    TOOLTIPS: {
      SORT_BY_ART_NR: 'Sort by Article Number',
      SORT_BY_PICTURES: 'Sort by Picture Count',
      SORT_BY_TITLE: 'Sort by Product Title',
      SORT_BY_LOCATIONS: 'Sort by Location Count',
      SORT_BY_QUANTITY: 'Sort by Available Quantity',
      SORT_BY_SALES_VOLUME: 'Sort by Sales Volume',
      SORT_BY_STATUS: 'Sort by Status',
      VIEW_PRODUCT_DETAILS: 'View Product Details',
      PICTURES_COUNT: '{count} image{s} available',
      AVAILABLE_IN_LOCATIONS: 'Available in {count} location{s}',
      QUANTITY_AVAILABLE: '{count} units currently available',
      TOTAL_REVENUE: 'Total revenue since product launch: {amount} €',
      STATUS_ACTIVE: 'Product is active and visible to users',
      STATUS_INACTIVE: 'Product is inactive and hidden from users',
    },
    FILTERS: {
      STATUS_ACTIVE: 'Active',
      STATUS_INACTIVE: 'Inactive',
    },
    STATUS: {
      PRODUCTS_COUNT: '{count} product{s} found',
      SORTED: '(sorted)',
    },
    PAGINATION: {
      SHOWING_TEXT: 'Showing {start}-{end} of {total} product{s}',
      PRODUCT_SINGULAR: 'product',
      PRODUCT_PLURAL: 'products',
    },
    EMPTY_STATE: {
      NO_PRODUCTS_FOUND: 'No products found',
      NO_PRODUCTS_MATCHING: 'No products found matching "{search}"',
    },
    CONSOLE_MESSAGES: {
      VIEW_PRODUCT_DETAILS: 'View product details:',
      STATUS_CHANGED: 'Product status changed:',
    },
    MODAL: {
      TITLE: 'Product Details',
      FIELDS: {
        ART_NR: 'Article Number',
        TITLE: 'Product Title',
        STATUS: 'Status',
        PICTURES: 'Pictures',
        LOCATIONS: 'Available Locations',
        QUANTITY: 'Available Quantity',
        SALES_VOLUME: 'Total Sales Volume',
        DESCRIPTION: 'Description',
        CATEGORY: 'Category',
        MANUFACTURER: 'Manufacturer',
        PRICE: 'Unit Price',
        CREATED_DATE: 'Created Date',
        LAST_UPDATED: 'Last Updated',
      },
    },
  },
  LOCATIONS_TABLE: {
    TITLE: 'Locations Management',
    PLACEHOLDERS: {
      SEARCH: 'Search locations...',
      NAME: 'Enter location name',
      ADDRESS: 'Enter location address',
      TYPE: 'Select location type',
    },
    ACTIONS: {
      ADD: 'Add Location',
      ASSIGN: 'Assign Location',
      EDIT: 'Edit',
    },
    ERRORS: {
      NAME: 'Please enter a location name',
      ADDRESS: 'Please enter a location address',
      TYPE: 'Please select a location type',
    },
    COLUMNS: {
      NAME: 'Name',
      ADDRESS: 'Address',
      TYPE: 'Type',
      STATUS: 'Status',
      LOCATION_ID: 'Location ID',
      USER: 'User',
      AREA: 'Area',
      COVER: 'Cover',
      ARTICLES: 'Articles',
      LOGISTIC: 'Logistic',
      SALES_VOLUME: 'Sales Volume',
      DATE_CREATED: 'Date Created',
      ACTIONS: 'Actions',
    },
    SEARCH: {
      PLACEHOLDER: 'Search locations...',
      QUICK_SORT: 'Quick Sort',
    },
    SORT_OPTIONS: {
      NEWEST_FIRST: 'Newest First',
      OLDEST_FIRST: 'Oldest First',
      SALES_HIGH_TO_LOW: 'Sales Volume (High to Low)',
      SALES_LOW_TO_HIGH: 'Sales Volume (Low to High)',
      MOST_ARTICLES: 'Most Articles',
      FEWEST_ARTICLES: 'Fewest Articles',
      USER_NAME_A_TO_Z: 'User Name (A-Z)',
      USER_NAME_Z_TO_A: 'User Name (Z-A)',
    },
    TOOLTIPS: {
      SORT_BY_LOCATION_ID: 'Sort by Location ID',
      SORT_BY_USER_NAME: 'Sort by User Name',
      SORT_BY_AREA: 'Sort by Area',
      SORT_BY_COVERAGE: 'Sort by Coverage',
      SORT_BY_ARTICLE_COUNT: 'Sort by Article Count',
      SORT_BY_LOGISTIC_TYPE: 'Sort by Logistic Type',
      SORT_BY_SALES_VOLUME: 'Sort by Sales Volume',
      SORT_BY_CREATION_DATE: 'Sort by Creation Date (Oldest/Newest)',
      VIEW_LOCATION_DETAILS: 'View Location Details',
      TOTAL_REVENUE: 'Total revenue: {amount} €',
      ESTABLISHED: 'Established: {date}',
    },
    FILTERS: {
      COVER_YES: 'Ja',
      COVER_NO: 'Ne',
    },
    STATUS: {
      LOCATION_COUNT: '{count} location{s} found',
      SORTED: '(sorted)',
      ACTIVE: 'Active',
      INACTIVE: 'Inactive',
      MAINTENANCE: 'Maintenance',
    },
    PAGINATION: {
      SHOWING_TEXT: 'Showing {start}-{end} of {total} location{s}',
      LOCATION_SINGULAR: 'location',
      LOCATION_PLURAL: 'locations',
    },
    EMPTY_STATE: {
      NO_LOCATIONS_FOUND: 'No locations found',
      NO_LOCATIONS_MATCHING: 'No locations found matching "{search}"',
    },
    CONSOLE_MESSAGES: {
      VIEW_LOCATION_DETAILS: 'View location details:',
      LOCATION_ID_CLICKED: 'Location ID clicked:',
    },
    MODAL: {
      TITLE: {
        ADD: 'Add New Location',
        ASSIGN: 'Assign Existing Location',
        EDIT: 'Edit Location',
        DEFAULT: 'Location',
      },
      FIELDS: {
        SELECT_LOCATION: 'Select Location',
        ASSIGNMENT_TYPE: 'Assignment Type',
        LOCATION_ID: 'Location ID',
        NAME: 'Location Name',
        ADDRESS: 'Address',
        TYPE: 'Location Type',
        STATUS: 'Status',
      },
      PLACEHOLDERS: {
        SELECT_LOCATION: 'Choose from existing locations',
        ASSIGNMENT_TYPE: 'Select assignment type',
        LOCATION_ID: 'e.g., LOC001',
        NAME: 'e.g., Main Office, Warehouse A',
        ADDRESS: 'Full address including street, city, state, zip code',
        TYPE: 'Select type',
      },
      ERRORS: {
        SELECT_LOCATION: 'Please select a location',
        ASSIGNMENT_TYPE: 'Please select assignment type',
        LOCATION_ID: 'Please enter location ID',
        NAME: 'Please enter location name',
        ADDRESS: 'Please enter address',
        TYPE: 'Please select location type',
        STATUS: 'Please select status',
      },
    },
    ASSIGNMENT_TYPES: {
      PRIMARY: 'Primary Location',
      SECONDARY: 'Secondary Location',
      TEMPORARY: 'Temporary Access',
    },
    TYPES: {
      OFFICE: 'Office',
      WAREHOUSE: 'Warehouse',
      DISTRIBUTION_CENTER: 'Distribution Center',
      RETAIL_STORE: 'Retail Store',
      MANUFACTURING: 'Manufacturing',
    },
    MESSAGES: {
      ADD_SUCCESS: 'Location added successfully!',
      ASSIGN_SUCCESS: 'Location assigned successfully!',
      UPDATE_SUCCESS: 'Location updated successfully!',
    },
  },
  LOGISTICS_TABLE: {
    TITLE: 'Logistics Management',
    COLUMNS: {
      LOGISTIC_NR: 'Logistic Nr',
      NAME: 'Name',
      TYPE: 'Type',
      REGION: 'Region',
      LOCATION: 'Location',
      TOURS: 'Tours',
      SALES_VOLUME: 'Sales Volume',
      ACTIONS: 'Actions',
    },
    SEARCH: {
      PLACEHOLDER: 'Search logistics carriers...',
      QUICK_SORT: 'Quick Sort',
    },
    SORT_OPTIONS: {
      NEWEST_FIRST: 'Newest First',
      OLDEST_FIRST: 'Oldest First',
      SALES_HIGH_TO_LOW: 'Sales Volume (High to Low)',
      SALES_LOW_TO_HIGH: 'Sales Volume (Low to High)',
      MOST_TOURS: 'Most Tours',
      FEWEST_TOURS: 'Fewest Tours',
      MOST_REGIONS: 'Most Regions',
      FEWEST_REGIONS: 'Fewest Regions',
      NAME_A_TO_Z: 'Name (A-Z)',
      NAME_Z_TO_A: 'Name (Z-A)',
    },
    TOOLTIPS: {
      SORT_BY_LOGISTIC_NR: 'Sort by Logistic Number',
      SORT_BY_NAME: 'Sort by Name',
      SORT_BY_TYPE: 'Sort by Type',
      SORT_BY_REGIONS: 'Sort by Region Count',
      SORT_BY_LOCATIONS: 'Sort by Location Count',
      SORT_BY_TOURS: 'Sort by Tour Count',
      SORT_BY_SALES_VOLUME: 'Sort by Sales Volume',
      VIEW_LOGISTICS_DETAILS: 'View Logistics Details',
      TOTAL_REVENUE: 'Total revenue: {amount} €',
      COVERS_REGIONS: 'Covers {count} regions',
      COVERS_LOCATIONS: 'Covers {count} locations',
      TOURS_COMPLETED: '{count} tours completed',
    },
    STATUS: {
      LOGISTICS_COUNT: '{count} logistics carrier{s} found',
      SORTED: '(sorted)',
    },
    PAGINATION: {
      SHOWING_TEXT: 'Showing {start}-{end} of {total} logistics carrier{s}',
      LOGISTICS_SINGULAR: 'logistics carrier',
      LOGISTICS_PLURAL: 'logistics carrier',
    },
    EMPTY_STATE: {
      NO_LOGISTICS_FOUND: 'No logistics carriers found',
      NO_LOGISTICS_MATCHING: 'No logistics carriers found matching "{search}"',
    },
    CONSOLE_MESSAGES: {
      VIEW_LOGISTICS_DETAILS: 'View logistics details:',
      LOGISTICS_ID_CLICKED: 'Logistics ID clicked:',
    },
    MODAL: {
      TITLE: 'Logistics Details',
      FIELDS: {
        LOGISTIC_NR: 'Logistic Number',
        NAME: 'Company Name',
        TYPE: 'Service Type',
        STATUS: 'Status',
        ADDRESS: 'Address',
        PHONE: 'Phone',
        EMAIL: 'Email',
        REGIONS: 'Regions Coverage',
        LOCATIONS: 'Locations Coverage',
        TOURS: 'Total Tours',
        SALES_VOLUME: 'Sales Volume',
        ESTABLISHED_DATE: 'Established Date',
        LAST_ACTIVITY: 'Last Activity',
      },
    },
  },
  USER_DETAILS_MODAL: {
    TITLE: 'User Details',
    COMPANY_DATA: 'Company Data',
    ERRORS: {
      COMPANY_NAME: 'Please enter a company name',
      COMPANY_ID: 'Please enter a company ID',
      COMPANY_PHONE: 'Please enter a company phone number',
      COMPANY_FAX: 'Please enter a company fax number',
      COMPANY_EMAIL: 'Please enter a company email',
    },
    PLACEHOLDERS: {
      COMPANY_NAME: 'Enter company name',
      COMPANY_ID: 'Enter company ID',
      COMPANY_PHONE: 'Enter company phone number',
      COMPANY_FAX: 'Enter company fax number',
      COMPANY_EMAIL: 'Enter company email',
      ADDRESS: 'Enter company address',
    },
    LABELS: {
      COMPANY_NAME: 'Company Name',
      COMPANY_ID: 'Company ID',
      COMPANY_PHONE: 'Company Phone',
      COMPANY_FAX: 'Company Fax',
      COMPANY_EMAIL: 'Company Email',
      USER_ID: 'User ID',
      FIRST_NAME: 'First Name',
      LAST_NAME: 'Last Name',
      PROFILE_NAME: 'Profile Name',
      EMAIL: 'Email',
      PHONE: 'Phone',
      MOBILE: 'Mobile',
      FAX: 'Fax',
      ADDRESS: 'Address',
      USER_TYPES: 'User Types',
      ROLE: 'Role',
      STATUS: 'Status',
      DEPARTMENT: 'Department',
      LOCATION: 'Location',
      JOIN_DATE: 'Join Date',
      LAST_LOGIN: 'Last Login',
      ACTIVE_WAREHOUSES: 'Active Warehouses',
      TOTAL_ORDERS: 'Total Orders',
      TOTAL_PURCHASE_AMOUNT: 'Total Purchase Amount',
      LISTED_ARTICLES: 'Listed Articles',
      TOTAL_SALES: 'Total Sales',
      TOTAL_SALES_AMOUNT: 'Total Sales Amount',
      ROLE_ADMINISTRATION_IT: 'Administration IT',
      ROLE_AREA_MANAGEMENT: 'Area Management',
      ROLE_OPERATIONS_MANAGEMENT: 'Operations Management',
      ROLE_ACCOUNTING: 'Accounting',
      ROLE_CONTROLLING: 'Controlling',
      ROLE_LOGISTICS_COORDINATOR: 'Logistics Coordinator',
      ROLE_PURCHASING: 'Purchasing',
      ROLE_MANAGEMENT: 'Management',
      ROLE_CUSTOMER_SUPPORT: 'Customer Support',
      ROLE_WAREHOUSING: 'Warehousing',
      ROLE_WAREHOUSE_MANAGEMENT: 'Warehouse Management',
      ROLE_LOGISTICS: 'Logistics',
      ROLE_PROJECT_MANAGEMENT: 'Project Management',
      ROLE_ADMINISTRATIVE: 'Administrative',
      ROLE_SECRETARY: 'Secretary',
      ROLE_SALES: 'Sales',
    },
    NO_ACTIVE_WAREHOUSES: 'No active warehouses',
  },
  CONTACT_PERSONS_TABLE: {
    TITLE: 'Contact Persons',
    COLUMNS: {
      CONTACT_ID: 'Contact ID',
      FIRST_NAME: 'First Name',
      LAST_NAME: 'Last Name',
      EMAIL: 'Email',
      PHONE: 'Phone',
      POSITION: 'Position',
      DEPARTMENT: 'Department',
      STATUS: 'Status',
      ACTIONS: 'Actions',
    },
    LABELS: {
      FIRST_NAME: 'First Name',
      LAST_NAME: 'Last Name',
      EMAIL: 'Email',
      PHONE: 'Phone',
      POSITION: 'Position',
      DEPARTMENT: 'Department',
      SEARCH: 'Search Contacts',
    },
    PLACEHOLDERS: {
      FIRST_NAME: 'Enter first name',
      LAST_NAME: 'Enter last name',
      EMAIL: 'Enter email address',
      PHONE: 'Enter phone number',
      POSITION: 'Enter position',
      DEPARTMENT: 'Enter department',
      SEARCH: 'Search contacts...',
    },
    ERRORS: {
      FIRST_NAME: 'Please input first name!',
      LAST_NAME: 'Please input last name!',
      EMAIL: 'Please input email!',
      EMAIL_INVALID: 'Please enter a valid email!',
      PHONE: 'Please input phone number!',
      POSITION: 'Please input position!',
      DEPARTMENT: 'Please input department!',
    },
    ACTIONS: {
      ADD: 'Add Contact',
      ASSIGN: 'Assign Contact',
      EDIT: 'Edit',
    },
  },
  COMMON: {
    CANCEL: 'Cancel',
    RESET: 'Reset',
    CONFIRM_DISCARD_TITLE: 'Discard Changes?',
    CONFIRM_DISCARD_MESSAGE: 'Are you sure you want to discard your changes?',
    DISCARD: 'Discard',
  },
  EMPLOYEES_TABLE: {
    TITLE: 'Employees',
    COLUMNS: {
      NAME: 'Name',
      POSITION: 'Position',
      EMAIL: 'Email',
      PHONE: 'Phone',
      LOCATION: 'Location',
      STATUS: 'Status',
      ACTIONS: 'Actions',
    },
    LABELS: {
      NAME: 'Name',
      POSITION: 'Position',
      EMAIL: 'Email',
      PHONE: 'Phone',
      LOCATION: 'Location',
      STATUS: 'Status',
      SEARCH: 'Search Employees',
    },
    PLACEHOLDERS: {
      NAME: 'Enter name',
      POSITION: 'Enter position',
      EMAIL: 'Enter email address',
      PHONE: 'Enter phone number',
      LOCATION: 'Select location',
      SEARCH: 'Search employees...',
    },
    ERRORS: {
      NAME: 'Please input name!',
      POSITION: 'Please input position!',
      EMAIL: 'Please input email!',
      EMAIL_INVALID: 'Please enter a valid email!',
      PHONE: 'Please input phone number!',
      LOCATION: 'Please select a location!',
    },
    ACTIONS: {
      ADD: 'Add Employee',
      EDIT: 'Edit',
      DELETE: 'Delete',
    },
    STATUS: {
      ACTIVE: 'Active',
      INACTIVE: 'Inactive',
    },
    EMPTY_STATE: {
      NO_EMPLOYEES: 'No employees found',
      NO_LOCATIONS: 'Please add locations first to manage employees',
    },
    MESSAGES: {
      ADD_SUCCESS: 'Employee added successfully',
      UPDATE_SUCCESS: 'Employee updated successfully',
      DELETE_SUCCESS: 'Employee deleted successfully',
      ADD_ERROR: 'Failed to add employee',
      UPDATE_ERROR: 'Failed to update employee',
      DELETE_ERROR: 'Failed to delete employee',
    },
    MODAL: {
      TITLE: {
        ADD: 'Add New Employee',
        EDIT: 'Edit Employee',
      },
      FIELDS: {
        NAME: 'Employee Name',
        POSITION: 'Position',
        EMAIL: 'Email Address',
        PHONE: 'Phone Number',
        LOCATION: 'Location',
        STATUS: 'Status',
      },
      ERRORS: {
        NAME: 'Please enter employee name',
        POSITION: 'Please enter position',
        EMAIL: 'Please enter email',
        EMAIL_INVALID: 'Please enter a valid email',
        PHONE: 'Please enter phone number',
        LOCATION: 'Please select a location',
        STATUS: 'Please select status',
      },
      PLACEHOLDERS: {
        NAME: 'Full name',
        POSITION: 'Job title',
        EMAIL: 'Email address',
        PHONE: 'Phone number',
        LOCATION: 'Select location',
      },
    },
  },
  EDIT_USER_FORM: {
    TITLE: 'Edit User',
    TABS: {
      DETAILS: 'Details',
      LOCATION: 'Location',
      EMPLOYEES: 'Employees',
      ORDERS: 'Order History',
      SALES: 'Sales History',
      OFFERINGS: 'Offerings',
      ORG_CHART: 'Organizational Chart',
    },
    MESSAGES: {
      UPDATE_SUCCESS: 'User updated successfully',
      UPDATE_ERROR: 'Failed to update user',
      LOAD_ERROR: 'Failed to load user data',
      USER_NOT_FOUND: 'User not found',
    },
    BUTTONS: {
      SAVE: 'Save',
      CANCEL: 'Cancel',
      BACK: 'Back to Users',
    },
    LOADING: {
      FETCHING: 'Loading user data...',
      SAVING: 'Saving changes...',
    },
  },
  ORDER_HISTORY: {
    TITLE: 'Order History',
    SUBTITLE: 'All past and current orders',
    NO_ORDERS: 'No orders found',
    STATUS: {
      PENDING: 'Pending',
      PROCESSING: 'Processing',
      SHIPPED: 'Shipped',
      DELIVERED: 'Delivered',
      CANCELLED: 'Cancelled',
      REFUNDED: 'Refunded',
    },
  },
  SALES_HISTORY: {
    TITLE: 'Sales History',
    SUBTITLE: 'All past and current sales',
    NO_SALES: 'No sales found',
    COMPLETED_SALES: 'Completed Sales',
    TOTAL_REVENUE: 'Total Revenue',
    STATUS: {
      PENDING: 'Pending',
      PROCESSING: 'Processing',
      SHIPPED: 'Shipped',
      DELIVERED: 'Delivered',
      CANCELLED: 'Cancelled',
      REFUNDED: 'Refunded',
    },
  },
  OFFERINGS: {
    TITLE: 'Current Offerings',
    SUBTITLE: 'All current offerings with their respective quantities',
    NO_OFFERINGS: 'No offerings found',
    TOTAL_ITEMS: 'Total Items',
    TOTAL_QUANTITY: 'Total Quantity',
    COLUMNS: {
      ITEM_NAME: 'Item Name',
      CATEGORY: 'Category',
      QUANTITY: 'Quantity',
      PRICE: 'Price',
      LOCATION: 'Location',
      STATUS: 'Status',
    },
    STATUS: {
      ACTIVE: 'Active',
      INACTIVE: 'Inactive',
      OUT_OF_STOCK: 'Out of Stock',
    },
  },
  ORGANIZATIONAL_CHART: {
    TITLE: 'Organizational Chart',
    SUBTITLE: 'Company structure showing locations and employees',
    NO_DATA: 'No organizational data available',
    LOCATION: {
      HEAD: 'Head Location',
      BRANCH: 'Branch Location',
    },
    EMPLOYEE: {
      POSITION: 'Position',
      DEPARTMENT: 'Department',
    },
  },
};
