export const COMPANY_CONTACTS = {
  TITLE: 'Company Contacts',
  ADD_CONTACT: 'Add Contact',
  ADD_CONTACT_PERSON: 'Create New Contact Person',
  EDIT_CONTACT: 'Edit Contact',
  DELETE_CONTACT: 'Delete Contact',
  CONTACT_LIST: 'Contact List',
  CONTACT_DETAILS: 'Contact Details',
  CONTACT_PERSONS: 'Contact Persons',
  NAME_LAST_NAME: 'Name - Last Name',
  USER_ID: 'User ID',
  LOCATION: 'Location',
  ROLE: 'Role',
  COMPANY_NAME: 'Company Name',
  COMPANY_ADDRESS: 'Company Address',
  EMAIL: 'Email',
  PHONE: 'Phone',
  MOBILE_PHONE: 'Mobile Phone',
  REGISTRATION_DATE: 'Registration Date',
  STATUS: 'Status',
  COMPANY_FOUNDERS: 'Company Founders',
  SEARCH_FOUNDERS: 'Search Founders',
  NO_FOUNDERS_FOUND: 'No Founders Found',
  NO_FOUNDERS_FOUND_MATCHING: 'No Founders Found Matching',
  TOTAL_FOUNDERS: 'Total Founders',
  SORT_BY: 'Sort By',
  // Modal sections
  MODAL: {
    SECTIONS: {
      COMPANY: 'Company',
      LOCATION: 'Location',
      CONTACT_PERSON_INFO: 'Contact Person Information',
    },
    FIELDS: {
      FIRST_NAME: 'First Name',
      LAST_NAME: 'Last Name',
      ADDRESS: 'Address',
      PHONE_NUMBER: 'Phone Number',
      MOBILE_NUMBER: 'Mobile Number',
    },
    PLACEHOLDERS: {
      SELECT_COMPANY: 'Select a company',
      SELECT_LOCATION: 'Select a location',
      ENTER_FIRST_NAME: 'Enter first name',
      ENTER_LAST_NAME: 'Enter last name',
      ENTER_EMAIL: 'Enter email address',
      ENTER_PHONE: 'Enter phone number (e.g., +49 30 12345678)',
      ENTER_MOBILE: 'Enter mobile number (e.g., +49 170 1234567)',
      ENTER_ADDRESS: 'Enter full address (street, city, postal code, country)',
    },
    VALIDATION: {
      SELECT_COMPANY: 'Please select a company!',
      SELECT_LOCATION: 'Please select a location!',
      ENTER_FIRST_NAME: 'Please enter first name!',
      ENTER_LAST_NAME: 'Please enter last name!',
      ENTER_EMAIL: 'Please enter email!',
      ENTER_PHONE: 'Please enter phone number!',
      ENTER_MOBILE: 'Please enter mobile number!',
      ENTER_ADDRESS: 'Please enter address!',
      FIRST_NAME_MIN: 'First name must be at least 2 characters!',
      LAST_NAME_MIN: 'Last name must be at least 2 characters!',
      FIRST_NAME_MAX: 'First name cannot exceed 50 characters!',
      LAST_NAME_MAX: 'Last name cannot exceed 50 characters!',
      EMAIL_MAX: 'Email cannot exceed 100 characters!',
      PHONE_MAX: 'Phone number cannot exceed 20 characters!',
      MOBILE_MAX: 'Mobile number cannot exceed 20 characters!',
      ADDRESS_MIN: 'Address must be at least 10 characters!',
      ADDRESS_MAX: 'Address cannot exceed 200 characters!',
      VALID_EMAIL: 'Please enter a valid email address!',
      VALID_EMAIL_FORMAT: 'Please enter a valid email format (e.g., user@example.com)!',
      VALID_PHONE_FORMAT: 'Please enter a valid phone number format!',
      VALID_MOBILE_FORMAT: 'Please enter a valid mobile number format!',
      PHONE_MIN_DIGITS: 'Phone number must be at least 7 digits!',
      MOBILE_MIN_DIGITS: 'Mobile number must be at least 7 digits!',
      FIRST_NAME_PATTERN: 'First name can only contain letters, spaces, hyphens, and apostrophes!',
      LAST_NAME_PATTERN: 'Last name can only contain letters, spaces, hyphens, and apostrophes!',
    },
    BUTTONS: {
      CANCEL: 'Cancel',
      SAVE: 'Save',
    },
    MESSAGES: {
      SUCCESS: 'Contact person created successfully!',
      ERROR: 'Failed to create contact person. Please try again.',
    },
  },
  ROLES: {
    ADMINISTRATOR: 'Administrator',
    AREA_MANAGEMENT: 'Area management',
    OPERATIONS_MANAGEMENT: 'Operations management',
    ACCCOUNTING: 'Acccounting',
    CONTROLLING: 'Controlling',
    LOGISTICS_COORDINATOR: 'Logistics coordinator',
    PURCHASING: 'Purchasing',
    MANAGEMENT: 'Management',
    CUSTOMER_SUPPORT: 'Customersupport',
    WAREHOUSING: 'Warehousing',
    WAREHOUSE_MANAGEMENT: 'Warehouse management',
    LOGISTICS: 'Logistics',
    PROJECT_MANAGEMENT: 'Project management',
    ADMIN_ISTRATIVE: 'Admin istrative',
    SECRETARY: 'Secretary',
    SALES: 'Sales',
  },
};
