export const COMPANY_CONTACTS = {
  TITLE: 'Kontakte',
  ADD_CONTACT: 'Kontakt hinzufügen',
  ADD_CONTACT_PERSON: 'Neue Kontaktperson erstellen',
  EDIT_CONTACT: 'Kontakt bearbeiten',
  DELETE_CONTACT: 'Kontakt löschen',
  CONTACT_LIST: 'Kontaktliste',
  CONTACT_DETAILS: 'Kontaktdetails',
  CONTACT_PERSONS: 'Kontaktpersonen',
  NAME_LAST_NAME: 'Name - Nachname',
  USER_ID: 'Benutzer-ID',
  LOCATION: 'Standort',
  ROLE: 'Rolle',
  COMPANY_NAME: 'Firma',
  COMPANY_ADDRESS: 'Adresse',
  EMAIL: 'E-Mail',
  PHONE: 'Telefon',
  MOBILE_PHONE: 'Mobiltelefon',
  REGISTRATION_DATE: 'Registrierungsdatum',
  STATUS: 'Status',
  COMPANY_FOUNDERS: 'Unternehmensgründer',
  SEARCH_FOUNDERS: 'Unternehmensgründer suchen',
  NO_FOUNDERS_FOUND: 'Keine Unternehmensgründer gefunden',
  NO_FOUNDERS_FOUND_MATCHING: 'Keine Unternehmensgründer gefunden, die mit "%s" übereinstimmen',
  TOTAL_FOUNDERS: 'Gesamtzahl der Unternehmensgründer',
  SORT_BY: 'Sortieren nach',
  // Modal sections
  MODAL: {
    SECTIONS: {
      COMPANY: 'Unternehmen',
      LOCATION: 'Standort',
      CONTACT_PERSON_INFO: 'Kontaktpersonen-Informationen',
    },
    FIELDS: {
      FIRST_NAME: 'Vorname',
      LAST_NAME: 'Nachname',
      ADDRESS: 'Adresse',
      PHONE_NUMBER: 'Telefonnummer',
      MOBILE_NUMBER: 'Mobilnummer',
    },
    PLACEHOLDERS: {
      SELECT_COMPANY: 'Unternehmen auswählen',
      SELECT_LOCATION: 'Standort auswählen',
      ENTER_FIRST_NAME: 'Vorname eingeben',
      ENTER_LAST_NAME: 'Nachname eingeben',
      ENTER_EMAIL: 'E-Mail-Adresse eingeben',
      ENTER_PHONE: 'Telefonnummer eingeben (z.B. +49 30 12345678)',
      ENTER_MOBILE: 'Mobilnummer eingeben (z.B. +49 170 1234567)',
      ENTER_ADDRESS: 'Vollständige Adresse eingeben (Straße, Stadt, PLZ, Land)',
    },
    VALIDATION: {
      SELECT_COMPANY: 'Bitte wählen Sie ein Unternehmen aus!',
      SELECT_LOCATION: 'Bitte wählen Sie einen Standort aus!',
      ENTER_FIRST_NAME: 'Bitte geben Sie den Vornamen ein!',
      ENTER_LAST_NAME: 'Bitte geben Sie den Nachnamen ein!',
      ENTER_EMAIL: 'Bitte geben Sie eine E-Mail-Adresse ein!',
      ENTER_PHONE: 'Bitte geben Sie eine Telefonnummer ein!',
      ENTER_MOBILE: 'Bitte geben Sie eine Mobilnummer ein!',
      ENTER_ADDRESS: 'Bitte geben Sie eine Adresse ein!',
      FIRST_NAME_MIN: 'Vorname muss mindestens 2 Zeichen lang sein!',
      LAST_NAME_MIN: 'Nachname muss mindestens 2 Zeichen lang sein!',
      FIRST_NAME_MAX: 'Vorname darf maximal 50 Zeichen lang sein!',
      LAST_NAME_MAX: 'Nachname darf maximal 50 Zeichen lang sein!',
      EMAIL_MAX: 'E-Mail-Adresse darf maximal 100 Zeichen lang sein!',
      PHONE_MAX: 'Telefonnummer darf maximal 20 Zeichen lang sein!',
      MOBILE_MAX: 'Mobilnummer darf maximal 20 Zeichen lang sein!',
      ADDRESS_MIN: 'Adresse muss mindestens 10 Zeichen lang sein!',
      ADDRESS_MAX: 'Adresse darf maximal 200 Zeichen lang sein!',
      VALID_EMAIL: 'Bitte geben Sie eine gültige E-Mail-Adresse ein!',
      VALID_EMAIL_FORMAT:
        'Bitte geben Sie ein gültiges E-Mail-Format ein (z.B. benutzer@beispiel.com)!',
      VALID_PHONE_FORMAT: 'Bitte geben Sie ein gültiges Telefonnummer-Format ein!',
      VALID_MOBILE_FORMAT: 'Bitte geben Sie ein gültiges Mobilnummer-Format ein!',
      PHONE_MIN_DIGITS: 'Telefonnummer muss mindestens 7 Ziffern haben!',
      MOBILE_MIN_DIGITS: 'Mobilnummer muss mindestens 7 Ziffern haben!',
      FIRST_NAME_PATTERN:
        'Vorname darf nur Buchstaben, Leerzeichen, Bindestriche und Apostrophe enthalten!',
      LAST_NAME_PATTERN:
        'Nachname darf nur Buchstaben, Leerzeichen, Bindestriche und Apostrophe enthalten!',
    },
    BUTTONS: {
      CANCEL: 'Abbrechen',
      SAVE: 'Speichern',
    },
    MESSAGES: {
      SUCCESS: 'Kontaktperson erfolgreich erstellt!',
      ERROR: 'Kontaktperson konnte nicht erstellt werden. Bitte versuchen Sie es erneut.',
    },
  },
  ROLES: {
    ADMINISTRATOR: 'Administrator',
    AREA_MANAGEMENT: 'Bereichsleitung',
    OPERATIONS_MANAGEMENT: 'Betriebsleitung',
    ACCCOUNTING: 'Buchhaltung',
    CONTROLLING: 'Controlling',
    LOGISTICS_COORDINATOR: 'Logistikkoordinator',
    PURCHASING: 'Einkauf',
    MANAGEMENT: 'Geschäftsführung',
    CUSTOMER_SUPPORT: 'Kundenbetreuung',
    WAREHOUSING: 'Lagerist',
    WAREHOUSE_MANAGEMENT: 'Lagerleitung',
    LOGISTICS: 'Logistik',
    PROJECT_MANAGEMENT: 'Projektleitung',
    ADMIN_ISTRATIVE: 'Administrative',
    SECRETARY: 'Sekretariat',
    SALES: 'Verkauf',
  },
};
