export const PRODUCT = {
  TITLE: 'Produkt',

  ERRORS: {
    FETCH_FAILED: 'Fehler beim Laden des Produkts ',
    CREATE_FAILED: 'Fehler beim Erstellen des Produkts ',
    UPDATE_FAILED: 'Fehler beim Aktualisieren des Produkts ',
    DELETE_FAILED: 'Fehler beim Löschen des Produkts ',
  },

  ADDITIONAL_OPTIONS: {
    PALLET: 'Palette',
    PALLET_TYPE: 'Palettentyp',
    EXCHANGEABLE_PALLET: 'Tauschpalette',
    DANGEROUS: 'Gefährlich',
    FRAGILE: 'Zerbrechlich',
    STACKABLE: 'Stapelbar',
    NEUTRAL_PACKAGING: 'Neutrale Verpackung',
    TEMPERATURE_SENSITIVITY: 'Temperaturempfindlichkeit',
    MAX_TEMPERATURE: 'Max. Temperatur',
    MIN_TEMPERATURE: 'Min. Temperatur',
    DELIVERY_SENSITIVITY: 'Lieferempfindlichkeit',
    MAX_DELIVERY_TIME_IN_HOURS: 'Max. Lieferzeit in Stunden',
  },

  DIMENSIONS_AND_WEIGHT: {
    WIDTH: 'Breite (mm)',
    HEIGHT: 'Höhe (mm)',
    DEPTH: 'Tiefe (mm)',
    WEIGHT_AMOUNT: 'Gewichtsmenge',
    WEIGHT_UNIT: 'Gewichtseinheit',
    SELECT_WEIGHT_UNIT: 'Bitte wählen Sie eine Gewichtseinheit',
  },

  BASIC_INFORMATION: {
    NAME: 'Name',
    IDIN: 'IDIN',
    CONDITION: 'Zustand',
    PRODUCT_TAGS: 'Produkt-Tags',
    PRODUCT_VARIATIONS: 'Produktvarianten',
    PRODUCT_ATTRIBUTES: 'Produktattribute',
    EXCERPT: 'Auszug',
    DESCRIPTION: 'Beschreibung',
    EXTRA_INFORMATION: 'Zusätzliche Informationen',
    PRODUCT_IMAGES: 'Produktbilder',
    ENTER_NAME: 'Bitte geben Sie den Produktnamen ein',
    ENTER_IDIN: 'Bitte geben Sie die IDIN ein',
    SELECT_CONDITION: 'Bitte wählen Sie den Produktzustand',
    SELECT_TAGS: 'Bitte wählen Sie mindestens einen Tag',
    SELECT_VARIATIONS: 'Bitte wählen Sie mindestens eine Variante',
    SELECT_ATTRIBUTES: 'Bitte wählen Sie mindestens ein Attribut',
  },

  PRICING_AND_QUANTITY: {
    PRICE_PER_PACKAGE: 'Preis pro Paket',
    PRICE_PER_UNIT: 'Preis pro Einheit',
    MINIMUM_ORDER_QUANTITY: 'Mindestbestellmenge',
    MAXIMUM_QUANTITY_PER_ORDER: 'Maximale Menge pro Bestellung',
    POSITIVE_NUMBER: 'Muss eine positive Zahl sein',
  },

  TABLE: {
    COLUMNS: {
      ART_NR: 'Art-Nr',
      PICTURES: 'Bilder',
      TITLE: 'Titel',
      LOCATION: 'Standort',
      QUANTITY: 'Menge',
      SALES_VOLUME: 'Verkaufsvolumen',
      STATUS: 'Status',
      ACTIONS: 'Aktionen',
    },
    SEARCH: {
      PLACEHOLDER: 'Produkte suchen...',
      QUICK_SORT: 'Schnellsortierung',
    },
    SORT_OPTIONS: {
      SALES_HIGH_TO_LOW: 'Verkaufsvolumen (Hoch zu Niedrig)',
      SALES_LOW_TO_HIGH: 'Verkaufsvolumen (Niedrig zu Hoch)',
      LOCATIONS_HIGH_TO_LOW: 'Standorte (Hoch zu Niedrig)',
      LOCATIONS_LOW_TO_HIGH: 'Standorte (Niedrig zu Hoch)',
      QUANTITY_HIGH_TO_LOW: 'Menge (Hoch zu Niedrig)',
      QUANTITY_LOW_TO_HIGH: 'Menge (Niedrig zu Hoch)',
      PICTURES_HIGH_TO_LOW: 'Bilder (Hoch zu Niedrig)',
      PICTURES_LOW_TO_HIGH: 'Bilder (Niedrig zu Hoch)',
      TITLE_A_TO_Z: 'Titel (A-Z)',
      TITLE_Z_TO_A: 'Titel (Z-A)',
      ART_NR_A_TO_Z: 'Art-Nr (A-Z)',
      ART_NR_Z_TO_A: 'Art-Nr (Z-A)',
    },

    TOOLTIPS: {
      SORT_BY_ART_NR: 'Nach Artikelnummer sortieren',
      SORT_BY_TITLE: 'Nach Produkttitel sortieren',
      SORT_BY_LOCATIONS: 'Nach Standortanzahl sortieren',
      SORT_BY_QUANTITY: 'Nach verfügbarer Menge sortieren',
      SORT_BY_PICTURES: 'Nach Bildanzahl sortieren',
      SORT_BY_SALES_VOLUME: 'Nach Verkaufsvolumen sortieren',
      SORT_BY_STATUS: 'Nach Status sortieren',
      VIEW_PRODUCT_DETAILS: 'Produktdetails anzeigen',
      TOTAL_REVENUE: 'Gesamtumsatz: {amount} €',
      AVAILABLE_QUANTITY: '{count} Einheiten derzeit verfügbar',
      LOCATIONS_COUNT: 'Verfügbar in {count} Standorten',
      PICTURES_COUNT: '{count} Bilder',
      SINGLE_PICTURE: '1 Bild',
      NO_PICTURES: 'Keine Bilder',
      STATUS_ACTIVE: 'Produkt ist aktiv und für Benutzer verfügbar',
      STATUS_INACTIVE: 'Produkt ist inaktiv und für Benutzer verborgen',
    },
    FILTERS: {
      STATUS_ACTIVE: 'Aktiv',
      STATUS_INACTIVE: 'Inaktiv',
    },
    STATUS: {
      PRODUCT_COUNT: '{count} Produkt{s} gefunden',
      SORTED: '(sortiert)',
    },
    PAGINATION: {
      SHOWING_TEXT: 'Zeige {start}-{end} von {total} Produkt{s}',
      PRODUCT_SINGULAR: 'Produkt',
      PRODUCT_PLURAL: 'Produkte',
    },
    EMPTY_STATE: {
      NO_PRODUCTS_FOUND: 'Keine Produkte gefunden',
      NO_PRODUCTS_MATCHING: 'Keine Produkte gefunden, die "{search}" entsprechen',
    },
    CONSOLE_MESSAGES: {
      VIEW_PRODUCT_DETAILS: 'Produktdetails anzeigen:',
      STATUS_CHANGED: 'Produktstatus geändert:',
    },
    SWITCH: {
      ACTIVE: 'Aktiv',
      INACTIVE: 'Inaktiv',
    },
  },
} as const;
