export const PRODUCT = {
  TITLE: 'Product',

  ERRORS: {
    FETCH_FAILED: 'Failed to fetch product ',
    CREATE_FAILED: 'Failed to create product ',
    UPDATE_FAILED: 'Failed to update product ',
    DELETE_FAILED: 'Failed to delete product ',
  },

  ADDITIONAL_OPTIONS: {
    PALLET: 'Pallet',
    PALLET_TYPE: 'Pallet Type',
    EXCHANGEABLE_PALLET: 'Exchangeable Pallet',
    DANGEROUS: 'Dangerous',
    FRAGILE: 'Fragile',
    STACKABLE: 'Stackable',
    NEUTRAL_PACKAGING: 'Neutral Packaging',
    TEMPERATURE_SENSITIVITY: 'Temperature Sensitivity',
    MAX_TEMPERATURE: 'Max Temperature',
    MIN_TEMPERATURE: 'Min Temperature',
    DELIVERY_SENSITIVITY: 'Delivery Sensitivity',
    MAX_DELIVERY_TIME_IN_HOURS: 'Max Delivery Time In Hours',
  },

  DIMENSIONS_AND_WEIGHT: {
    WIDTH: 'Width (mm)',
    HEIGHT: 'Height (mm)',
    DEPTH: 'Depth (mm)',
    WEIGHT_AMOUNT: 'Weight Amount',
    WEIGHT_UNIT: 'Weight Unit',
    SELECT_WEIGHT_UNIT: 'Please select a weight unit',
  },

  BASIC_INFORMATION: {
    NAME: 'Name',
    IDIN: 'IDIN',
    CONDITION: 'Condition',
    PRODUCT_TAGS: 'Product Tags',
    PRODUCT_VARIATIONS: 'Product Variations',
    PRODUCT_ATTRIBUTES: 'Product Attributes',
    EXCERPT: 'Excerpt',
    DESCRIPTION: 'Description',
    EXTRA_INFORMATION: 'Extra Information',
    PRODUCT_IMAGES: 'Product Images',
    ENTER_NAME: 'Please enter the product name',
    ENTER_IDIN: 'Please enter the IDIN',
    SELECT_CONDITION: 'Please select the product condition',
    SELECT_TAGS: 'Please select at least one tag',
    SELECT_VARIATIONS: 'Please select at least one variation',
    SELECT_ATTRIBUTES: 'Please select at least one attribute',
  },

  PRICING_AND_QUANTITY: {
    PRICE_PER_PACKAGE: 'Price Per Package',
    PRICE_PER_UNIT: 'Price Per Unit',
    MINIMUM_ORDER_QUANTITY: 'Minimum Order Quantity',
    MAXIMUM_QUANTITY_PER_ORDER: 'Maximum Quantity Per Order',
    POSITIVE_NUMBER: 'Must be a positive number',
  },

  FORM_STEPS: {
    BASIC_INFORMATION: 'Basic Information',
    DIMENSIONS_AND_WEIGHT: 'Dimensions and Weight',
    PRICING_AND_QUANTITY: 'Pricing and Quantity',
    ADDITIONAL_OPTIONS: 'Additional Options',
  },

  TABLE: {
    TITLE: 'Products Management',
    COLUMNS: {
      ART_NR: 'Art-Nr',
      PICTURES: 'Pictures',
      TITLE: 'Title',
      LOCATION: 'Location',
      CROWD: 'Crowd',
      SALES_VOLUME: 'Sales volume',
      STATUS: 'Status',
      ACTIONS: 'Actions',
    },
    SEARCH: {
      PLACEHOLDER: 'Search products...',
      QUICK_SORT: 'Quick Sort',
    },
    SORT_OPTIONS: {
      NEWEST_FIRST: 'Newest First',
      OLDEST_FIRST: 'Oldest First',
      SALES_HIGH_TO_LOW: 'Sales Volume (High to Low)',
      SALES_LOW_TO_HIGH: 'Sales Volume (Low to High)',
      MOST_LOCATIONS: 'Most Locations',
      FEWEST_LOCATIONS: 'Fewest Locations',
      HIGHEST_QUANTITY: 'Highest Quantity',
      LOWEST_QUANTITY: 'Lowest Quantity',
      MOST_PICTURES: 'Most Pictures',
      FEWEST_PICTURES: 'Fewest Pictures',
      TITLE_A_TO_Z: 'Title (A-Z)',
      TITLE_Z_TO_A: 'Title (Z-A)',
      ART_NR_ASC: 'Art-Nr (Ascending)',
      ART_NR_DESC: 'Art-Nr (Descending)',
    },
    TOOLTIPS: {
      SORT_BY_ART_NR: 'Sort by Article Number',
      SORT_BY_TITLE: 'Sort by Product Title',
      SORT_BY_LOCATIONS: 'Sort by Location Count',
      SORT_BY_QUANTITY: 'Sort by Available Quantity',
      SORT_BY_PICTURES: 'Sort by Picture Count',
      SORT_BY_SALES_VOLUME: 'Sort by Sales Volume',
      SORT_BY_STATUS: 'Sort by Status',
      VIEW_PRODUCT_DETAILS: 'View Product Details',
      TOTAL_REVENUE: 'Total revenue: {amount} €',
      AVAILABLE_QUANTITY: '{count} units currently available',
      LOCATIONS_COUNT: 'Available in {count} locations',
      PICTURES_COUNT: '{count} images',
      SINGLE_PICTURE: '1 image',
      NO_PICTURES: 'No images',
      STATUS_ACTIVE: 'Product is active and available to users',
      STATUS_INACTIVE: 'Product is inactive and hidden from users',
    },
    FILTERS: {
      STATUS_ACTIVE: 'Active',
      STATUS_INACTIVE: 'Inactive',
    },
    STATUS: {
      PRODUCT_COUNT: '{count} product{s} found',
      SORTED: '(sorted)',
    },
    PAGINATION: {
      SHOWING_TEXT: 'Showing {start}-{end} of {total} product{s}',
      PRODUCT_SINGULAR: 'product',
      PRODUCT_PLURAL: 'products',
    },
    EMPTY_STATE: {
      NO_PRODUCTS_FOUND: 'No products found',
      NO_PRODUCTS_MATCHING: 'No products found matching "{search}"',
    },
    CONSOLE_MESSAGES: {
      VIEW_PRODUCT_DETAILS: 'View product details:',
      STATUS_CHANGED: 'Product status changed:',
    },
    SWITCH: {
      ACTIVE: 'Active',
      INACTIVE: 'Inactive',
    },
  },
} as const;
